remote_theme: mmistakes/minimal-mistakes
title: "Diep Dao"
author: "Diep Dao"
description: "A blog about interesting things."
url: "https://diepdaocs.github.io"
baseurl: "/blog"
repository: "diepdaocs/blog"
plugins:
  - jekyll-include-cache
