remote_theme: mmistakes/minimal-mistakes
title: "My Awesome Blog"
author: "Your Name"
description: "A blog about interesting things."
url: "https://diepdaocs.github.io"
baseurl: ""
repository: "diepdaocs/blog"
plugins:
  - jekyll-include-cache
